version: '3.7'

x-node-defaults: &node
  tty: true
  init: true
  image: node:10.24
  entrypoint: ["node"]
  working_dir: /root
  restart: always
  volumes:
    - ./:/root:cached
    - ./node_modules:/root/node_modules:delegated
    - yarn-cache:/.yarn-cache

x-env-defaults: &env
  NEW_RELIC_ENABLED: ${NEW_RELIC_ENABLED-0}
  NEW_RELIC_LICENSE_KEY: ${NEW_RELIC_LICENSE_KEY-(unset)}
  NODE_ENV: development
  OMEDA_APP_ID: ${OMEDA_APP_ID-(unset)}
  OMEDA_INPUT_ID: ${OMEDA_INPUT_ID-(unset)}
  RECAPTCHA_SITE_KEY: ${RECAPTCHA_SITE_KEY-(unset)}
  RECAPTCHA_SECRET_KEY: ${RECAPTCHA_SECRET_KEY-(unset)}
  SENDGRID_API_KEY: ${SENDGRID_API_KEY-(unset)}
  SENDGRID_DEV_TO: ${SENDGRID_DEV_TO-support@parameter1.com}
  YARN_CACHE_FOLDER: /.yarn-cache
  IDENTITYX_API_TOKEN: ${IDENTITYX_API_TOKEN-(unset)}
  IDENTITYX_GRAPHQL_URI: ${IDENTITYX_GRAPHQL_URI-https://identity-x.parameter1.com/graphql}
  BASE_BROWSE_GRAPHQL_URI: ${BASE_BROWSE_GRAPHQL_URI-https://base-browse.virgon.base.parameter1.com/graphql}
  EQUIPMENT_EXPERTS_GRAPHQL_URI: ${EQUIPMENT_EXPERTS_GRAPHQL_URI-https://equipment-experts.virgon.base.parameter1.com/graphql}
  ENABLE_CONTENT_METER: ${ENABLE_CONTENT_METER-false}
  IDX_NAV_ENABLE: ${IDX_NAV_ENABLE-false}

  RECAPTCHA_V3_SITE_KEY: ${RECAPTCHA_V3_SITE_KEY-(unset)}
  RECAPTCHA_V3_SECRET_KEY: ${RECAPTCHA_V3_SECRET_KEY-(unset)}

x-env-virgon-dev: &env-virgon-dev
  GRAPHQL_URI: ${GRAPHQL_URI-http://host.docker.internal:10103}
  OEMBED_URI: ${OEMBED_URI-https://host.docker.internal:10402}
  RSS_URI: ${RSS_URI-http://host.docker.internal:10203}
  SITEMAPS_URI: ${SITEMAPS_URI-http://host.docker.internal:10303}

x-env-leonis: &env-leonis
  GRAPHQL_URI: ${GRAPHQL_URI-https://graphql.leonis.base.parameter1.com}
  OEMBED_URI: ${OEMBED_URI-https://oembed.leonis.base.parameter1.com}
  RSS_URI: ${RSS_URI-https://rss.leonis.base.parameter1.com}
  SITEMAPS_URI: ${SITEMAPS_URI-https://sitemaps.leonis.base.parameter1.com}

x-env-virgon: &env-virgon
  GRAPHQL_URI: ${GRAPHQL_URI-https://graphql.virgon.base.parameter1.com}
  OEMBED_URI: ${OEMBED_URI-https://oembed.virgon.base.parameter1.com}
  RSS_URI: ${RSS_URI-https://rss.virgon.base.parameter1.com}
  SITEMAPS_URI: ${SITEMAPS_URI-https://sitemaps.virgon.base.parameter1.com}

x-site-command: &site-cmd
  entrypoint: ["node_modules/.bin/basecms-website"]
  command: ["dev", "index.js"]

volumes:
  yarn-cache: {}

services:
  terminal:
    <<: *node
    working_dir: /root
    entrypoint: ["/bin/bash"]
    environment:
      <<: *env

  yarn:
    <<: *node
    working_dir: /root
    entrypoint: ["yarn"]
    environment:
      <<: *env

  eqw:
    <<: *node
    <<: *site-cmd
    working_dir: /root/sites/equipmentworld.com
    environment:
      <<: *env
      <<: *env-virgon
      HOST: www-rr-eqw.dev.parameter1.com
      PORT: 80
      EXPOSED_PORT: 9901
      LIVERELOAD_PORT: 19901
      TENANT_KEY: randallreilly_all
      SITE_ID: 5fce562fd28860bc33b826d6
    hostname: www-rr-eqw.dev.parameter1.com
    ports:
      - "9901:80"
      - "19901:19901"

  tlc:
    <<: *node
    <<: *site-cmd
    working_dir: /root/sites/totallandscapecare.com
    environment:
      <<: *env
      <<: *env-virgon
      HOST: www-rr-tlc.dev.parameter1.com
      PORT: 80
      EXPOSED_PORT: 9902
      LIVERELOAD_PORT: 19902
      TENANT_KEY: randallreilly_all
      SITE_ID: 5fce563dd28860bc33b829c5
    hostname: www-rr-tlc.dev.parameter1.com
    ports:
      - "9902:80"
      - "19902:19902"

  tn:
    <<: *node
    <<: *site-cmd
    working_dir: /root/sites/truckersnews.com
    environment:
      <<: *env
      <<: *env-virgon
      HOST: www-rr-tn.dev.parameter1.com
      PORT: 80
      EXPOSED_PORT: 9903
      LIVERELOAD_PORT: 19903
      TENANT_KEY: randallreilly_all
      SITE_ID: 5fce6131d28860bc33c5b786
    hostname: www-rr-tn.dev.parameter1.com
    ports:
      - "9903:80"
      - "19903:19903"

  ccj:
    <<: *node
    <<: *site-cmd
    working_dir: /root/sites/ccjdigital.com
    environment:
      <<: *env
      <<: *env-virgon
      HOST: www-rr-ccj.dev.parameter1.com
      PORT: 80
      EXPOSED_PORT: 9904
      LIVERELOAD_PORT: 19904
      TENANT_KEY: randallreilly_all
      SITE_ID: 5fce5519d28860bc33b80a42
    hostname: www-rr-ccj.dev.parameter1.com
    ports:
      - "9904:80"
      - "19904:19904"

  hwt:
    <<: *node
    <<: *site-cmd
    working_dir: /root/sites/hardworkingtrucks.com
    environment:
      <<: *env
      <<: *env-virgon
      HOST: www-rr-hwt.dev.parameter1.com
      PORT: 80
      EXPOSED_PORT: 9905
      LIVERELOAD_PORT: 19905
      TENANT_KEY: randallreilly_all
      SITE_ID: 5fce557bd28860bc33b8140d
    hostname: www-rr-hwt.dev.parameter1.com
    ports:
      - "9905:80"
      - "19905:19905"

  ovd:
    <<: *node
    <<: *site-cmd
    working_dir: /root/sites/overdriveonline.com
    environment:
      <<: *env
      <<: *env-virgon
      HOST: www-rr-ovd.dev.parameter1.com
      PORT: 80
      EXPOSED_PORT: 9906
      LIVERELOAD_PORT: 19906
      TENANT_KEY: randallreilly_all
      SITE_ID: 5fce561dd28860bc33b823ce
    hostname: www-rr-ovd.dev.parameter1.com
    ports:
      - "9906:80"
      - "19906:19906"

  tps:
    <<: *node
    <<: *site-cmd
    working_dir: /root/sites/truckpartsandservice.com
    environment:
      <<: *env
      <<: *env-virgon
      HOST: www-rr-tps.dev.parameter1.com
      PORT: 80
      EXPOSED_PORT: 9907
      LIVERELOAD_PORT: 19907
      TENANT_KEY: randallreilly_all
      SITE_ID: 5fce55abd28860bc33b818d0
    hostname: www-rr-tps.dev.parameter1.com
    ports:
      - "9907:80"
      - "19907:19907"
