name: Deploy sites (staging)

on:
  push:
    tags:
      - '*'

jobs:
  version:
    runs-on: ubuntu-latest
    steps:
    - id: tag_version
      run: |
        REF=$(echo $GITHUB_REF | cut -d / -f 3)
        [[ "$GITHUB_REF" =~ ^refs/tags.*$ ]] && VERSION="$REF" || VERSION="${REF}-${GITHUB_SHA::7}"
        echo "version=$VERSION" >> $GITHUB_OUTPUT
    outputs:
      version: ${{ steps.tag_version.outputs.version }}

  notify-start:
    needs: [version]
    uses: parameter1/actions/.github/workflows/notify-start.yml@main
    secrets: inherit
    with:
      version: ${{ needs.version.outputs.version }}

  post-deploy-failure:
    if: failure()
    needs: [notify-start, deploy-sites]
    uses: parameter1/actions/.github/workflows/notify-fail.yml@main
    secrets: inherit
    with:
      slack-thread: ${{ needs.notify-start.outputs.slack-thread }}

  post-deploy-complete:
    if: success()
    needs: [notify-start, deploy-sites]
    uses: parameter1/actions/.github/workflows/notify-complete.yml@main
    secrets: inherit
    with:
      slack-thread: ${{ needs.notify-start.outputs.slack-thread }}

  ######################
  # Add websites here! #
  ######################

  build-sites:
    needs: [version]
    uses: parameter1/actions/.github/workflows/website-build-push-test.yml@main
    strategy:
      matrix:
        ###############################################
        #v# Make sure this matches the site matrix! #v#
        ###############################################
        site:
          - { dir: ccjdigital.com, stack: virgon, id: 5fce5519d28860bc33b80a42, account: randallreilly, tenant: randallreilly_all, rancher_label: randall-reilly-ccjdigital.com }
          - { dir: equipmentworld.com, stack: virgon, id: 5fce562fd28860bc33b826d6, account: randallreilly, tenant: randallreilly_all, rancher_label: randall-reilly-equipmentworld.com }
          - { dir: hardworkingtrucks.com, stack: virgon, id: 5fce557bd28860bc33b8140d, account: randallreilly, tenant: randallreilly_all, rancher_label: randall-reilly-hardworkingtrucks.com }
          - { dir: overdriveonline.com, stack: virgon, id: 5fce561dd28860bc33b823ce, account: randallreilly, tenant: randallreilly_all, rancher_label: randall-reilly-overdriveonline.com }
          - { dir: totallandscapecare.com, stack: virgon, id: 5fce563dd28860bc33b829c5, account: randallreilly, tenant: randallreilly_all, rancher_label: randall-reilly-totallandscapecare.com }
          - { dir: truckersnews.com, stack: virgon, id: 5fce6131d28860bc33c5b786, account: randallreilly, tenant: randallreilly_all, rancher_label: randall-reilly-truckersnews.com }
          - { dir: truckpartsandservice.com, stack: virgon, id: 5fce55abd28860bc33b818d0, account: randallreilly, tenant: randallreilly_all, rancher_label: randall-reilly-truckpartsandservice.com }
        ###############################################
        #^# Make sure this matches the site matrix! #^#
        ###############################################
    with:
      ecr_registry: ${{ vars.AWS_ECR_REGISTRY }}
      push: true
      site_account: ${{ matrix.site.account }}
      site_dir: ${{ matrix.site.dir }}
      site_version: ${{ needs.version.outputs.version }}
    secrets: inherit

  deploy-sites:
    needs: [version, build-sites]
    uses: parameter1/actions/.github/workflows/website-deploy-staging.yml@main
    strategy:
      matrix:
        ###############################################
        #v# Make sure this matches the site matrix! #v#
        ###############################################
        site:
          - { dir: ccjdigital.com, stack: virgon, id: 5fce5519d28860bc33b80a42, account: randallreilly, tenant: randallreilly_all, rancher_label: randall-reilly-ccjdigital.com }
          - { dir: equipmentworld.com, stack: virgon, id: 5fce562fd28860bc33b826d6, account: randallreilly, tenant: randallreilly_all, rancher_label: randall-reilly-equipmentworld.com }
          - { dir: hardworkingtrucks.com, stack: virgon, id: 5fce557bd28860bc33b8140d, account: randallreilly, tenant: randallreilly_all, rancher_label: randall-reilly-hardworkingtrucks.com }
          - { dir: overdriveonline.com, stack: virgon, id: 5fce561dd28860bc33b823ce, account: randallreilly, tenant: randallreilly_all, rancher_label: randall-reilly-overdriveonline.com }
          - { dir: totallandscapecare.com, stack: virgon, id: 5fce563dd28860bc33b829c5, account: randallreilly, tenant: randallreilly_all, rancher_label: randall-reilly-totallandscapecare.com }
          - { dir: truckersnews.com, stack: virgon, id: 5fce6131d28860bc33c5b786, account: randallreilly, tenant: randallreilly_all, rancher_label: randall-reilly-truckersnews.com }
          - { dir: truckpartsandservice.com, stack: virgon, id: 5fce55abd28860bc33b818d0, account: randallreilly, tenant: randallreilly_all, rancher_label: randall-reilly-truckpartsandservice.com }
        ###############################################
        #^# Make sure this matches the site matrix! #^#
        ###############################################
    with:
      ecr_registry: ${{ vars.AWS_ECR_REGISTRY }}
      rancher_label: ${{ matrix.site.rancher_label }}
      site_account: ${{ matrix.site.account }}
      site_dir: ${{ matrix.site.dir }}
      site_stack: ${{ matrix.site.stack }}
      site_version: ${{ needs.version.outputs.version }}
    secrets: inherit
