name: Integration Tests

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]

jobs:
  build-and-test-image:
    uses: parameter1/actions/.github/workflows/website-build-push-test.yml@main
    strategy:
      matrix:
        ###############################################
        #v# Make sure this matches the site matrix! #v#
        ###############################################
        site:
          - { id: 5fce5519d28860bc33b80a42, dir: ccjdigital.com, stack: virgon, account: randallreilly, tenant: randallreilly_all, rancher_label: randall-reilly-ccjdigital.com }
          - { id: 5fce562fd28860bc33b826d6, dir: equipmentworld.com, stack: virgon, account: randallreilly, tenant: randallreilly_all, rancher_label: randall-reilly-equipmentworld.com }
          - { id: 5fce557bd28860bc33b8140d, dir: hardworkingtrucks.com, stack: virgon, account: randallreilly, tenant: randallreilly_all, rancher_label: randall-reilly-hardworkingtrucks.com }
          - { id: 5fce561dd28860bc33b823ce, dir: overdriveonline.com, stack: virgon, account: randallreilly, tenant: randallreilly_all, rancher_label: randall-reilly-overdriveonline.com }
          - { id: 5fce563dd28860bc33b829c5, dir: totallandscapecare.com, stack: virgon, account: randallreilly, tenant: randallreilly_all, rancher_label: randall-reilly-totallandscapecare.com }
          - { id: 5fce6131d28860bc33c5b786, dir: truckersnews.com, stack: virgon, account: randallreilly, tenant: randallreilly_all, rancher_label: randall-reilly-truckersnews.com }
          - { id: 5fce55abd28860bc33b818d0, dir: truckpartsandservice.com, stack: virgon, account: randallreilly, tenant: randallreilly_all, rancher_label: randall-reilly-truckpartsandservice.com }
        ###############################################
        #^# Make sure this matches the site matrix! #^#
        ###############################################
    with:
      docker_image: website-${{ matrix.site.dir }}
      site_id: ${{ matrix.site.id }}
      site_host: ${{ matrix.site.dir }}
      infra_stack: ${{ matrix.site.stack }}
      tenant_key: ${{ matrix.site.tenant }}
      ecr_registry: ${{ vars.AWS_ECR_REGISTRY }}
